security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 1234
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      url: mongodb://user:12345@localhost:27017/piggymetrics?connectTimeoutMS=300000

server:
  context-path: /accounts
  port: 6000
